displayName=Shared Boss Uniques
author=Thomas Hoste
description=Uploads boss collection-log data and shows shared unique progress for all participating players.
tags=group,collection log,boss,uniques,shared
plugins=be.vdab.osrsplugin.runelite.GimBossUniquesPlugin
